<?php
/**
 * Created by PhpStorm.
 * User: bobroid
 * Date: 07.06.16
 * Time: 21:29
 */

namespace frontend\models;


use common\models\Category;
use common\models\GoodPhoto;
use common\models\GoodStore;

class Good extends \common\models\Good
{

    public static function find()
    {
        return parent::find()->with('photos')->with('category'); // TODO: Change the autogenerated stub
    }
    
    public function getPhoto(){
        if(empty($this->photos)){
            return new GoodPhoto();
        }
        
        return array_pop($this->photos);
    }

    public function getLink(){
        return $this->link.'-g'.$this->id;
    }

    public function getSecondPhoto(){
        if(empty($this->photos) || !array_key_exists(1, $this->photos)){
            return new GoodPhoto();
        }

        return $this->photos[1];
    }

}